### ISSUE TITLE
View Helpers not Working in Rails 3.1

### ISSUE THREAD

**Issue by JackCA** [nesquena/rabl#147]
I've got a setup like follows:
`node do |i|
{ created: time_ago_in_words(i.created_at)}
end`

and am receiving the following error:
```undefined method 'time_ago_in_words' for #Rabl::Engine:0x007fdeb3956ca0

```

I am using the head version of Rabl.
Is there something more I have to do to include such type of view helpers?
```
