### ISSUE TITLE
Caching Doesn't Work With Dalli 2.0

### ISSUE THREAD

**Issue by joeytheman** [nesquena/rabl#204]
Dalli 2.0 breaks caching in Rabl.

Specifiying

```
cache @user 
```

Returns when viewing the json page.

```
undefined method `[]' for nil:NilClass
```
